//POKEMON TEMPLATE{ name: '', number: '', type: ['', ''] }

let pokemonList = [
    { name: 'Bulbasaur', number: '1', type: ['grass', 'poison'] },
    { name: 'Ivysaur', number: '2', type: ['grass', 'poison'] },
    { name: 'Venusaur', number: '3', type: ['grass', 'poison'] },
    { name: 'Charmander', number: '4', type: ['fire'] },
    { name: 'Charmeleon', number: '5', type: ['fire'] },
    { name: 'Charizard', number: '6', type: ['fire', 'flying'] },
    { name: 'Squirtle', number: '7', type: ['water'] },
    { name: 'Wartortle', number: '8', type: ['water'] },
    { name: 'Blastoise', number: '9', type: ['water'] },
    { name: 'Caterpie', number: '10', type: ['Bug'] },
    { name: 'Metapod', number: '11', type: ['Bug'] },
    { name: 'Butterfree', number: '12', type: ['Bug', 'Flying'] },
    { name: 'Weedle', number: '13', type: ['Bug', 'Poison'] },
    { name: 'Kakuna', number: '14', type: ['Bug', 'Poison'] },
    { name: 'Beedrill', number: '15', type: ['Bug', 'Poison'] },
    { name: 'Pidgey', number: '16', type: ['Normal', 'Flying'] },
    { name: 'Pidgeotto', number: '17', type: ['Normal', 'Flying'] },
    { name: 'Pidgeot', number: '18', type: ['Normal', 'Flying'] },
    { name: 'Rattata', number: '19', type: ['Normal'] },
    { name: 'Raticate', number: '20', type: ['Normal'] },
    { name: 'Spearow', number: '21', type: ['Normal', 'Flying'] },
    { name: 'Fearow', number: '22', type: ['Normal', 'Flying'] },
    { name: 'Ekans', number: '23', type: ['Poison'] },
    { name: 'Arbok', number: '24', type: ['Poison'] },
    { name: 'Pikachu', number: '25', type: ['Electric'] },
    { name: 'Raichu', number: '26', type: ['Electric'] },
    { name: 'Sandshrew', number: '27', type: ['Ground'] },
    { name: 'Sandslash', number: '28', type: ['Ground'] },
    { name: 'Nidoran', number: '29', type: ['Poison'] },
    { name: 'Nidorina', number: '30', type: ['Poison'] },
    { name: 'Nidoqueen', number: '31', type: ['Poison', 'Ground'] },
    { name: 'Nidoran', number: '32', type: ['Poison'] },
    { name: 'Nidorino', number: '33', type: ['Poison'] },
    { name: 'Nidoking', number: '34', type: ['Poison', 'Ground'] },
    { name: 'Clafairy', number: '35', type: ['Fairy'] },
    { name: 'Clefable', number: '36', type: ['Fairy'] },
    { name: 'Vulpix', number: '37', type: ['Fire'] },
    { name: 'Ninetales', number: '38', type: ['Fire'] },
    { name: 'Jigglypuff', number: '39', type: ['Normal', 'Fairy'] },
    { name: 'Wigglytuff', number: '40', type: ['Normal', 'Fairy'] },
    { name: 'Zubat', number: '41', type: ['Poison', 'Flying'] },
    { name: 'Golbat', number: '42', type: ['Poison', 'Flying'] },
    { name: 'Oddish', number: '43', type: ['Grass', 'Poison'] },
    { name: 'Gloom', number: '44', type: ['Grass', 'Poison'] },
    { name: 'Vileplume', number: '45', type: ['Grass', 'Poison'] },
    { name: 'Paras', number: '46', type: ['Bug', 'Grass'] },
    { name: 'Parasect', number: '47', type: ['Bug', 'Grass'] },
    { name: 'Venonat', number: '48', type: ['Bug', 'Poison'] },
    { name: 'Venomoth', number: '49', type: ['Bug', 'Poison'] },
    { name: 'Diglett', number: '50', type: ['Ground'] },
    { name: 'Dugtrio', number: '51', type: ['Ground'] },
    { name: 'Meowth', number: '52', type: ['Normal'] },
    { name: 'Persian', number: '53', type: ['Normal'] },
    { name: 'Psyduck', number: '54', type: ['Water'] },
    { name: 'Golduck', number: '55', type: ['Water'] },
    { name: 'Mankey', number: '56', type: ['Fight'] },
    { name: 'Primeape', number: '57', type: ['Fight'] },
    { name: 'Growlithe', number: '58', type: ['Fire'] },
    { name: 'Arcanine', number: '59', type: ['Fire'] },
    { name: 'Poliwag', number: '60', type: ['Water'] },
    { name: 'Poliwhirl', number: '61', type: ['Water'] },
    { name: 'Poliwrath', number: '62', type: ['Water', 'Fight'] },
    { name: 'Abra', number: '63', type: ['Psychic'] },
    { name: 'Kadabra', number: '64', type: ['Psychic'] },
    { name: 'Alakazam', number: '65', type: ['Psychic'] },
    { name: 'Machop', number: '66', type: ['Fight'] },
    { name: 'Machoke', number: '67', type: ['Fight'] },
    { name: 'Machamp', number: '68', type: ['Fight'] },
    { name: 'Bellsprout', number: '69', type: ['Grass', 'Poison'] },
    { name: 'Weepinbell', number: '70', type: ['Grass', 'Poison'] },
    { name: 'Victreebel', number: '71', type: ['Grass', 'Poison'] },
    { name: 'Tentacool', number: '72', type: ['Water', 'Poison'] },
    { name: 'Tentaruel', number: '73', type: ['Water', 'Poison'] },
    { name: 'Geodude', number: '74', type: ['Rock', 'Ground'] },
    { name: 'Graveler', number: '75', type: ['Rock', 'Ground'] },
    { name: 'Golem', number: '76', type: ['Rock', 'Ground'] },
    { name: 'Ponyta', number: '77', type: ['Fire'] },
    { name: 'Rapidash', number: '78', type: ['Fire'] },
    { name: 'Slowpoke', number: '79', type: ['Water', 'Psychic'] },
    { name: 'Slowbro', number: '80', type: ['Water', 'Psychic'] },
    { name: 'Magnemite', number: '81', type: ['Electric', 'Steel'] },
    { name: 'Magneton', number: '82', type: ['Electric', 'Steel'] },
    { name: 'Farfetch´d', number: '83', type: ['Normal', 'Flying'] },
    { name: 'Doduo', number: '84', type: ['Normal', 'Flying'] },
    { name: 'Dodrio', number: '85', type: ['Normal', 'Flying'] },
    { name: 'Seel', number: '86', type: ['Water'] },
    { name: 'Dewgong', number: '87', type: ['Water', 'Ice'] },
    { name: 'Grimer', number: '88', type: ['Poison'] },
    { name: 'Muk', number: '89', type: ['Poison'] },
    { name: 'Shellder', number: '90', type: ['Water'] },
    { name: 'Cloyster', number: '91', type: ['Water', 'Ice'] },
    { name: 'Gastly', number: '92', type: ['Ghost', 'Poison'] },
    { name: 'Haunter', number: '93', type: ['Ghost', 'Poison'] },
    { name: 'Gengar', number: '94', type: ['Ghost', 'Poison'] },
    { name: 'Onix', number: '95', type: ['Rock', 'Ground'] },
    { name: 'Drowzee', number: '96', type: ['Psychic'] },
    { name: 'Hypno', number: '97', type: ['Psychic'] },
    { name: 'Krabby', number: '98', type: ['Water'] },
    { name: 'Kingler', number: '99', type: ['Water'] },
    { name: 'Voltorb', number: '100', type: ['Electric'] },
    { name: 'Electrode', number: '101', type: ['Electric'] },
    { name: 'Exeggcute', number: '102', type: ['Grass', 'Psychic'] },
    { name: 'Exeggutor', number: '103', type: ['Grass', 'Psychic'] },
    { name: 'Cubone', number: '104', type: ['Gound'] },
    { name: 'Marowak', number: '105', type: ['Ground'] },
    { name: 'Hitmonlee', number: '106', type: ['Fight'] },
    { name: 'hitmonchan', number: '107', type: ['Fight'] },
    { name: 'Lickytung', number: '108', type: ['Normal'] },
    { name: 'Koffing', number: '109', type: ['Poison'] },
    { name: 'Weezing', number: '110', type: ['Poison'] },
    { name: 'Rhyhorn', number: '111', type: ['Ground', 'Rock'] },
    { name: 'Rhydon', number: '112', type: ['Ground', 'Rock'] },
    { name: 'Chansey', number: '113', type: ['Nprmal'] },
    { name: 'Tangela', number: '114', type: ['Grass'] },
    { name: 'Kangaskhan', number: '115', type: ['Water'] },
    { name: 'Horsea', number: '116', type: ['Water'] },
    { name: 'Seadra', number: '117', type: ['Water'] },
    { name: 'Goldeen', number: '118', type: ['Water'] },
    { name: 'Seaking', number: '119', type: ['Water'] },
    { name: 'Staryu', number: '120', type: ['Water'] },
    { name: 'Starmie', number: '121', type: ['Water', 'Psychic'] },
    { name: 'Mr.Mime', number: '122', type: ['Psychic', 'Fairy'] },
    { name: 'Scyther', number: '123', type: ['Bug', 'Flying'] },
    { name: 'Jynx', number: '124', type: ['Ice', 'Psychic'] },
    { name: 'Electabuzz', number: '125', type: ['Electric'] },
    { name: 'Magmar', number: '126', type: ['Fire'] },
    { name: 'Pinsir', number: '127', type: ['Bug'] },
    { name: 'Tauros', number: '128', type: ['Normal'] },
    { name: 'Magicarp', number: '129', type: ['Water'] },
    { name: 'Gyarados', number: '130', type: ['Water', 'Flying'] },
    { name: 'Lapras', number: '131', type: ['Water', 'Ice'] },
    { name: 'Ditto', number: '132', type: ['Normal'] },
    { name: 'Eevee', number: '133', type: ['Normal'] },
    { name: 'Vaporeon', number: '134', type: ['Water'] },
    { name: 'Jolton', number: '135', type: ['Electric'] },
    { name: 'Flareon', number: '136', type: ['Fire'] },
    { name: 'Porygorn', number: '137', type: ['Normal'] },
    { name: 'Omanyte', number: '138', type: ['Rock', 'Water'] },
    { name: 'Omastar', number: '139', type: ['Rock', 'Water'] },
    { name: 'Kabuto', number: '140', type: ['Rock', 'Water'] },
    { name: 'Kabutops', number: '141', type: ['Rock', 'Water'] },
    { name: 'Aerodactyl', number: '142', type: ['Rock', 'Flying'] },
    { name: 'Snorlax', number: '143', type: ['Normal'] },
    { name: 'Articuno', number: '144', type: ['Ice', 'Flying'] },
    { name: 'Zapdos', number: '145', type: ['Electric', 'Flying'] },
    { name: 'Moltres', number: '146', type: ['Fire', 'Flying'] },
    { name: 'Dratini', number: '147', type: ['Dragon'] },
    { name: 'Dragonair', number: '148', type: ['Dragon'] },
    { name: 'Dragonite', number: '149', type: ['Dragon', 'Flying'] },
    { name: 'Mewtwo', number: '150', type: ['Psychic'] },
    { name: 'Mew', number: '151', type: ['Psychic'] },
]