//POKEMON TEMPLATE{ name: '', number: '', type: ['', ''] }

let pokemonList = [
    { name: 'Bulbasaur', number: '1', height: '0.7', type: ['grass', 'poison'] },
    { name: 'Ivysaur', number: '2', height: '1', type: ['grass', 'poison'] },
    { name: 'Venusaur', number: '3', height: '2', type: ['grass', 'poison'] },
    { name: 'Charmander', number: '4', height: '0.6', type: ['fire'] },
    { name: 'Charmeleon', number: '5', height: '1.1', type: ['fire'] },
    { name: 'Charizard', number: '6', height: '1.7', type: ['fire', 'flying'] },
    { name: 'Squirtle', number: '7', height: '0.5', type: ['water'] },
    { name: 'Wartortle', number: '8', height: '1', type: ['water'] },
    { name: 'Blastoise', number: '9', height: '1.6', type: ['water'] },
    { name: 'Caterpie', number: '10', height: '0.3', type: ['Bug'] },
    { name: 'Metapod', number: '11', height: '0.7', type: ['Bug'] },
    { name: 'Butterfree', number: '12', height: '1.1', type: ['Bug', 'Flying'] },
    { name: 'Weedle', number: '13', height: '0.3', type: ['Bug', 'Poison'] },
    { name: 'Kakuna', number: '14', height: '0.6', type: ['Bug', 'Poison'] },
    { name: 'Beedrill', number: '15', height: '1', type: ['Bug', 'Poison'] },
    { name: 'Pidgey', number: '16', height: '0.3', type: ['Normal', 'Flying'] },
    { name: 'Pidgeotto', number: '17', height: '1.1', type: ['Normal', 'Flying'] },
    { name: 'Pidgeot', number: '18', height: '1.5', type: ['Normal', 'Flying'] },
    { name: 'Rattata', number: '19', height: '0.5', type: ['Normal'] },
    { name: 'Raticate', number: '20', height: '0.7', type: ['Normal'] },
    { name: 'Spearow', number: '21', height: '0.3', type: ['Normal', 'Flying'] },
    { name: 'Fearow', number: '22', height: '1.2', type: ['Normal', 'Flying'] },
    { name: 'Ekans', number: '23', height: '2', type: ['Poison'] },
    { name: 'Arbok', number: '24', height: '3.5', type: ['Poison'] },
    { name: 'Pikachu', number: '25', height: '0.4', type: ['Electric'] },
    { name: 'Raichu', number: '26', height: '0.8', type: ['Electric'] },
    { name: 'Sandshrew', number: '27', height: '0.6', type: ['Ground'] },
    { name: 'Sandslash', number: '28', height: '1', type: ['Ground'] },
    { name: 'Nidoran', number: '29', height: '0.4', type: ['Poison'] },
    { name: 'Nidorina', number: '30', height: '0.8', type: ['Poison'] },
    { name: 'Nidoqueen', number: '31', height: '1.3', type: ['Poison', 'Ground'] },
    { name: 'Nidoran', number: '32', height: '0.5', type: ['Poison'] },
    { name: 'Nidorino', number: '33', height: '0.9', type: ['Poison'] },
    { name: 'Nidoking', number: '34', height: '1.5', type: ['Poison', 'Ground'] },
    { name: 'Clafairy', number: '35', height: '0.6', type: ['Fairy'] },
    { name: 'Clefable', number: '36', height: '1.3', type: ['Fairy'] },
    { name: 'Vulpix', number: '37', height: '0.6', type: ['Fire'] },
    { name: 'Ninetales', number: '38', height: '1.1', type: ['Fire'] },
    { name: 'Jigglypuff', number: '39', height: '0.5', type: ['Normal', 'Fairy'] },
    { name: 'Wigglytuff', number: '40', height: '1', type: ['Normal', 'Fairy'] },
    { name: 'Zubat', number: '41', height: '0.8', type: ['Poison', 'Flying'] },
    { name: 'Golbat', number: '42', height: '1.6', type: ['Poison', 'Flying'] },
    { name: 'Oddish', number: '43', height: '0.5', type: ['Grass', 'Poison'] },
    { name: 'Gloom', number: '44', height: '0.8', type: ['Grass', 'Poison'] },
    { name: 'Vileplume', number: '45', height: '1.2', type: ['Grass', 'Poison'] },
    { name: 'Paras', number: '46', height: '0.3', type: ['Bug', 'Grass'] },
    { name: 'Parasect', number: '47', height: '1', type: ['Bug', 'Grass'] },
    { name: 'Venonat', number: '48', height: '1', type: ['Bug', 'Poison'] },
    { name: 'Venomoth', number: '49', height: '1.5', type: ['Bug', 'Poison'] },
    { name: 'Diglett', number: '50', height: '0.2', type: ['Ground'] },
    { name: 'Dugtrio', number: '51', height: '0.7', type: ['Ground'] },
    { name: 'Meowth', number: '52', height: '0.4', type: ['Normal'] },
    { name: 'Persian', number: '53', height: '1', type: ['Normal'] },
    { name: 'Psyduck', number: '54', height: '0.8', type: ['Water'] },
    { name: 'Golduck', number: '55', height: '1.7', type: ['Water'] },
    { name: 'Mankey', number: '56', height: '0.5', type: ['Fight'] },
    { name: 'Primeape', number: '57', height: '1', type: ['Fight'] },
    { name: 'Growlithe', number: '58', height: '0.7', type: ['Fire'] },
    { name: 'Arcanine', number: '59', height: '1.9', type: ['Fire'] },
    { name: 'Poliwag', number: '60', height: '0.6', type: ['Water'] },
    { name: 'Poliwhirl', number: '61', height: '1', type: ['Water'] },
    { name: 'Poliwrath', number: '62', height: '1.3', type: ['Water', 'Fight'] },
    { name: 'Abra', number: '63', height: '0.9', type: ['Psychic'] },
    { name: 'Kadabra', number: '64', height: '1.3', type: ['Psychic'] },
    { name: 'Alakazam', number: '65', height: '1.5', type: ['Psychic'] },
    { name: 'Machop', number: '66', height: '0.8', type: ['Fight'] },
    { name: 'Machoke', number: '67', height: '1.5', type: ['Fight'] },
    { name: 'Machamp', number: '68', height: '1.6', type: ['Fight'] },
    { name: 'Bellsprout', number: '69', height: '0.7', type: ['Grass', 'Poison'] },
    { name: 'Weepinbell', number: '70', height: '1', type: ['Grass', 'Poison'] },
    { name: 'Victreebel', number: '71', height: '1.7', type: ['Grass', 'Poison'] },
    { name: 'Tentacool', number: '72', height: '0.9', type: ['Water', 'Poison'] },
    { name: 'Tentaruel', number: '73', height: '1.6', type: ['Water', 'Poison'] },
    { name: 'Geodude', number: '74', height: '0.4', type: ['Rock', 'Ground'] },
    { name: 'Graveler', number: '75', height: '1', type: ['Rock', 'Ground'] },
    { name: 'Golem', number: '76', height: '1.4', type: ['Rock', 'Ground'] },
    { name: 'Ponyta', number: '77', height: '1', type: ['Fire'] },
    { name: 'Rapidash', number: '78', height: '1.7', type: ['Fire'] },
    { name: 'Slowpoke', number: '79', height: '1.2', type: ['Water', 'Psychic'] },
    { name: 'Slowbro', number: '80', height: '1.6', type: ['Water', 'Psychic'] },
    { name: 'Magnemite', number: '81', height: '0.3', type: ['Electric', 'Steel'] },
    { name: 'Magneton', number: '82', height: '1', type: ['Electric', 'Steel'] },
    { name: 'Farfetch´d', number: '83', height: '0.8', type: ['Normal', 'Flying'] },
    { name: 'Doduo', number: '84', height: '1.4', type: ['Normal', 'Flying'] },
    { name: 'Dodrio', number: '85', height: '1.8', type: ['Normal', 'Flying'] },
    { name: 'Seel', number: '86', height: '1.1', type: ['Water'] },
    { name: 'Dewgong', number: '87', height: '1.7', type: ['Water', 'Ice'] },
    { name: 'Grimer', number: '88', height: '0.9', type: ['Poison'] },
    { name: 'Muk', number: '89', height: '1.2', type: ['Poison'] },
    { name: 'Shellder', number: '90', height: '0.3', type: ['Water'] },
    { name: 'Cloyster', number: '91', height: '1.5', type: ['Water', 'Ice'] },
    { name: 'Gastly', number: '92', height: '1.3', type: ['Ghost', 'Poison'] },
    { name: 'Haunter', number: '93', height: '1.6', type: ['Ghost', 'Poison'] },
    { name: 'Gengar', number: '94', height: '1.5', type: ['Ghost', 'Poison'] },
    { name: 'Onix', number: '95', height: '8.8', type: ['Rock', 'Ground'] },
    { name: 'Drowzee', number: '96', height: '1', type: ['Psychic'] },
    { name: 'Hypno', number: '97', height: '1.6', type: ['Psychic'] },
    { name: 'Krabby', number: '98', height: '0.4', type: ['Water'] },
    { name: 'Kingler', number: '99', height: '1.3', type: ['Water'] },
    { name: 'Voltorb', number: '100', height: '0.5', type: ['Electric'] },
    { name: 'Electrode', number: '101', height: '1.2', type: ['Electric'] },
    { name: 'Exeggcute', number: '102', height: '0.4', type: ['Grass', 'Psychic'] },
    { name: 'Exeggutor', number: '103', height: '2', type: ['Grass', 'Psychic'] },
    { name: 'Cubone', number: '104', height: '0.4', type: ['Gound'] },
    { name: 'Marowak', number: '105', height: '1', type: ['Ground'] },
    { name: 'Hitmonlee', number: '106', height: '1.5', type: ['Fight'] },
    { name: 'Hitmonchan', number: '107', height: '1.4', type: ['Fight'] },
    { name: 'Lickytung', number: '108', height: '1.2', type: ['Normal'] },
    { name: 'Koffing', number: '109', height: '0.6', type: ['Poison'] },
    { name: 'Weezing', number: '110', height: '1.2', type: ['Poison'] },
    { name: 'Rhyhorn', number: '111', height: '1', type: ['Ground', 'Rock'] },
    { name: 'Rhydon', number: '112', height: '1.9', type: ['Ground', 'Rock'] },
    { name: 'Chansey', number: '113', height: '1.1', type: ['Nprmal'] },
    { name: 'Tangela', number: '114', height: '1', type: ['Grass'] },
    { name: 'Kangaskhan', number: '115', height: '2.2', type: ['Water'] },
    { name: 'Horsea', number: '116', height: '0.4', type: ['Water'] },
    { name: 'Seadra', number: '117', height: '1.2', type: ['Water'] },
    { name: 'Goldeen', number: '118', height: '0.6', type: ['Water'] },
    { name: 'Seaking', number: '119', height: '1.3', type: ['Water'] },
    { name: 'Staryu', number: '120', height: '0.8', type: ['Water'] },
    { name: 'Starmie', number: '121', height: '1.1', type: ['Water', 'Psychic'] },
    { name: 'Mr.Mime', number: '122', height: '1.3', type: ['Psychic', 'Fairy'] },
    { name: 'Scyther', number: '123', height: '1.5', type: ['Bug', 'Flying'] },
    { name: 'Jynx', number: '124', height: '1.4', type: ['Ice', 'Psychic'] },
    { name: 'Electabuzz', number: '125', height: '1.1', type: ['Electric'] },
    { name: 'Magmar', number: '126', height: '1.3', type: ['Fire'] },
    { name: 'Pinsir', number: '127', height: '1.5', type: ['Bug'] },
    { name: 'Tauros', number: '128', height: '1.4', type: ['Normal'] },
    { name: 'Magicarp', number: '129', height: '0.9', type: ['Water'] },
    { name: 'Gyarados', number: '130', height: '6.5', type: ['Water', 'Flying'] },
    { name: 'Lapras', number: '131', height: '2.5', type: ['Water', 'Ice'] },
    { name: 'Ditto', number: '132', height: '0.3', type: ['Normal'] },
    { name: 'Eevee', number: '133', height: '0.3', type: ['Normal'] },
    { name: 'Vaporeon', number: '134', height: '1', type: ['Water'] },
    { name: 'Jolton', number: '135', height: '0.8', type: ['Electric'] },
    { name: 'Flareon', number: '136', height: '0.9', type: ['Fire'] },
    { name: 'Porygon', number: '137', height: '0.8', type: ['Normal'] },
    { name: 'Omanyte', number: '138', height: '0.4', type: ['Rock', 'Water'] },
    { name: 'Omastar', number: '139', height: '1', type: ['Rock', 'Water'] },
    { name: 'Kabuto', number: '140', height: '0.5', type: ['Rock', 'Water'] },
    { name: 'Kabutops', number: '141', height: '1.3', type: ['Rock', 'Water'] },
    { name: 'Aerodactyl', number: '142', height: '1.8', type: ['Rock', 'Flying'] },
    { name: 'Snorlax', number: '143', height: '2.1', type: ['Normal'] },
    { name: 'Articuno', number: '144', height: '1.7', type: ['Ice', 'Flying'] },
    { name: 'Zapdos', number: '145', height: '1.6', type: ['Electric', 'Flying'] },
    { name: 'Moltres', number: '146', height: '2', type: ['Fire', 'Flying'] },
    { name: 'Dratini', number: '147', height: '1.8', type: ['Dragon'] },
    { name: 'Dragonair', number: '148', height: '4', type: ['Dragon'] },
    { name: 'Dragonite', number: '149', height: '2.2', type: ['Dragon', 'Flying'] },
    { name: 'Mewtwo', number: '150', height: '2', type: ['Psychic'] },
    { name: 'Mew', number: '151', height: '0.4', type: ['Psychic'] },
]
